### ISSUE TITLE
Selected date and time

### ISSUE THREAD

**Issue by icidasset** [PanagiotisGeorgiadis/Elm-DatePicker#1]
Hi!

Thanks for this package, great stuff! ☺️ 
I was wondering why it's not possible to pass an initial date/time?
(ie. pass a date/time to `initialise`, which would be the initial `selectedDate`)

If you think it's a good idea, I can make a PR if need be.
Thanks again ✌️ 

PS. While I'm at it, any thoughts about AM/PM input?

**Comment by PanagiotisGeorgiadis** [comment]
Hello @icidasset and thanks for raising this issue! 😃 

Its a really cool suggestion that I've missed while developing this package so please feel free to implement and raise a PR! I've also wanted to do some more improvements on the DatePicker cause it is in an early stage I think ( aimed to make it as basic as possible ).

So on AM/PM, I don't think that there is a necessity to add it since we can be more accurate with the 24h selector. If you have this as a requirement maybe we can give it some thought and come up with something. 😄
