### ISSUE TITLE
The ellie link on the documentation goes to an empty ellie.

### ISSUE THREAD

**Issue by NikosEfthias** [PanagiotisGeorgiadis/Elm-DatePicker#4]
Hi, 
The ellie link you shared on the front page on package.elm-lang.org is pointing to an empty ellie

**Comment by PanagiotisGeorgiadis** [comment]
Hello there, I was unable to write a proper Ellie example since we've had the _well known_ issue with the compiler crashing while using the `--debug` flag.

The latest version of the README file should contain links to a different [repository](https://github.com/PanagiotisGeorgiadis/Elm-DatePicker-examples) I've created in order to write down some examples ( also contains the styling used for the date pickers ).

Please let me know if you think that something is wrong with either the examples or README. :smile:
